project_id = "cjgyelmkjgwgwbwydddz"

[functions.chat]
verify_jwt = false

[functions.sarvam-stt]
verify_jwt = false

[functions.sarvam-tts]
verify_jwt = false

[functions.schedule-call]
verify_jwt = false

[functions.trigger-scheduled-calls]
verify_jwt = false
